# Generated by Django 5.0.7 on 2024-07-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='avatar',
            field=models.ImageField(null='True', upload_to='company/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='bio',
            field=models.TextField(null='True'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='bio',
            field=models.TextField(null='True'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='category',
            field=models.CharField(max_length=100, null='True'),
        ),
    ]
