# Generated by Django 5.0.7 on 2024-07-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_company_contact_email_company_contact_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
