# Generated by Django 5.0.7 on 2024-07-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_driver_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('full-time', 'full-time'), ('part-time', 'part-time'), ('contract', 'contract')], default='open', max_length=10),
        ),
    ]
