# Generated by Django 5.0.7 on 2024-07-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('full-time', 'full-time'), ('part-time', 'part-time'), ('contract', 'contract')], default='full-time', max_length=10),
        ),
    ]
