# Generated by Django 5.0.7 on 2024-07-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0010_remove_job_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='motivation_letter',
            field=models.TextField(default=''),
        ),
    ]
